/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Application {
  constructor()
  get(pattern: string, handler: RouteHandler): void
  post(pattern: string, handler: RouteHandler): void
  put(pattern: string, handler: RouteHandler): void
  /**
   * Binds a TCP listener on `port` and starts accepting connections in the
   * background, dispatching each parsed request to the first registered
   * route whose method and path pattern match.
   */
  start(port: number): void
}

/** A simple HTTP request struct that can be used to represent an HTTP request in a web application. */
export declare class HttpRequest {
  constructor(method: Method, path: string, headers: Array<Header>, body: string, queryParams: Record<string, string>, pathParams: Record<string, string>)
  get method(): Method
  get path(): string
  get headers(): Array<Header>
  get body(): string
  get queryParams(): Record<string, string>
  get pathParams(): Record<string, string>
  set method(method: Method)
  set path(path: string)
  set headers(headers: Array<Header>)
  set body(body: string)
  set queryParams(queryParams: Record<string, string>)
  set pathParams(pathParams: Record<string, string>)
}

/** Maps an HTTP method and path pattern to the handler that serves it. */
export declare class Route {
  /** The HTTP method this route matches (e.g. `"GET"`). */
  method: string
  /**
   * The path pattern this route matches, e.g. `"/users"` or, with a path
   * parameter, `"/location/:id"`.
   */
  pattern: string
  constructor(method: string, pattern: string, handler: RouteHandler)
}

export interface Header {
  name: string
  value: string
}

/**
 * A plain-data HTTP response: a `#[napi(object)]`, not a `#[napi]` class,
 * so it converts to/from JS by value (a real `FromNapiValue` impl) rather
 * than by reference. That's required for `RouteHandler` (src/http_route.rs)
 * to get a genuine owned `HttpResponse` back out of a JS handler's return
 * value — `#[napi]` classes only support owned-value conversion one way
 * (Rust -> JS), so a class-typed `HttpResponse` could never make it back
 * across a `ThreadsafeFunction` call synchronously. JS mutates this like
 * any plain object (`res.statusCode = ...`) and must `return res;`.
 */
export interface HttpResponse {
  statusCode: number
  headers: Array<Header>
  body: string
}

/** An HTTP request method. */
export type Method =
  | { type: 'Get' }
  | { type: 'Post' }
  | { type: 'Put' }
  | { type: 'Patch' }
  | { type: 'Other', field0: string }

export type RouteHandler =
  ((arg0: HttpRequest, arg1: HttpResponse) => HttpResponse)
