/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A simple HTTP request struct that can be used to represent an HTTP request in a web application. */
export declare class HttpRequest {
  constructor(method: string, url: string, headers: Array<Header>, body: string, queryParams: Record<string, string>, pathParams: Record<string, string>)
  get method(): string
  get url(): string
  get headers(): Array<Header>
  get body(): string
  get queryParams(): Record<string, string>
  get pathParams(): Record<string, string>
  set method(method: string)
  set url(url: string)
  set headers(headers: Array<Header>)
  set body(body: string)
  set queryParams(queryParams: Record<string, string>)
  set pathParams(pathParams: Record<string, string>)
}

export interface Header {
  name: string
  value: string
}

export declare function startTcpListener(port: number): void
